services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    user: userpy
    volumes:
      - ../:/usr/src/app
      - pipcache:/home/userpy/.cache/pip
    environment:
    - PYTHONUNBUFFERED=1
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${VIRTUAL_HOST}'
      - 'traefik.docker.network=${PROXY_NETWORK}'
      - 'traefik.port=${VIRTUAL_PORT}'

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db:
  pipcache:
    external: true
    
networks:
  default:
    external: true
    name: ${PROXY_NETWORK}